# -*- coding: utf-8 -*-
"""Dashboard Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFZyTu0Ug-ebJmGpNto8zk6zGz5Hq_dk

# H1N1 Visualization
"""

! pip install -U kaleido
! pip install --upgrade "kaleido==0.1.*"

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import kaleido
from PIL import Image
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


# Load the data into a Pandas DataFrame
df = pd.read_csv("/content/data.csv")

# Rename columns
df = df.rename(columns={"Cumulative no. of cases": "Infections", "Cumulative no. of deaths": "Deaths"})

df.head()

# Bar chart showing total number of deaths vs total number of infections
fig2 = plt.figure(figsize=(8, 5))
plt.bar(["Infections", "Deaths"], [df["Infections"].sum(), df["Deaths"].sum()])
plt.title("Total Number of Deaths vs Total Number of Infections", fontdict={'fontsize': 16, 'fontweight': 'bold', 'fontfamily': 'serif'})
plt.xlabel("Outcome")
plt.ylabel("Number of Cases")
plt.show()
plt.tight_layout()
fig2.savefig("dashboard2.png")

# Choropleth showing the number of infections per country
fig = px.choropleth(df, locations="Country", locationmode="country names", color="Infections", hover_name="Country",
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.update_layout(title={'text': '<b>Number of Infections per Country</b>',
        'font': {'size': 26, 'family': 'serif'},
        'x':0.5,
        'xanchor':'center'})
fig.show()
fig.write_image("dashboard1.png")

# Line graph showing the daily change in the total number of deaths and total number of infections
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d")
df_daily = df.groupby("Date")[["Infections", "Deaths"]].sum().reset_index()
fig, ax = plt.subplots()
ax.plot(df_daily["Date"], df_daily["Infections"], label="Infections")
ax.plot(df_daily["Date"], df_daily["Deaths"], label="Deaths")
ax.legend()
plt.title("Change in Number of Infections and Deaths", fontdict={'fontsize': 16, 'fontweight': 'bold', 'fontfamily': 'serif'})
plt.xlabel("Date")
plt.ylabel("Number of Cases")
plt.show()
fig.savefig("dashboard3.png")

# Group the data by country and calculate the total number of infections
df_country = df.groupby("Country")["Infections"].sum().reset_index()

# Sort the data by the total number of infections in descending order
df_country = df_country.sort_values(by="Infections", ascending=False)

# Create a bar chart showing the top 10 countries by infection rate
top_10_countries = df_country.head(10)
sns.set_style("whitegrid")
fig4 = plt.figure(figsize=(12, 6))
sns.barplot(x="Country", y="Infections", data=top_10_countries, palette="viridis")
plt.title("Top 10 Countries by Infection Rate", fontdict={'fontsize': 16, 'fontweight': 'bold', 'fontfamily': 'serif'})
plt.xlabel("Country")
plt.ylabel("Number of Infections")
plt.show()
plt.tight_layout()
fig4.savefig("dashboard4.png")

fig_final = plt.figure(figsize=(24, 16))
fig_final.text(x=0.5, y=1, s="H1N1 Swine Flu 2009 Pandemic Dashboard", fontsize=26, ha="center")
fig_final.text(x=0.5, y=0.98, s= "Student Name:_________ Student Number: ____________", fontsize=12, ha="center")
plt.subplot(2, 2, 1)
plt.imshow(plt.imread("dashboard1.png"))
plt.axis('off')
plt.subplot(2, 2, 2)
plt.imshow(plt.imread("dashboard2.png"))
plt.axis('off')
plt.subplot(2, 2, 3)
plt.imshow(plt.imread("dashboard3.png"))
plt.axis('off')
plt.subplot(2, 2, 4)
plt.imshow(plt.imread("dashboard4.png"))
plt.axis('off')
plt.tight_layout()
plt.savefig("dashboard.png")